package com.sessionm.smp_auth.sessionm;

import android.content.Intent;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.TextView;
import android.widget.Toast;

import com.sessionm.core.api.SessionM;
import com.sessionm.core.api.SessionMError;
import com.sessionm.core.api.provider.AuthenticationProvider;
import com.sessionm.identity.api.UserManager;
import com.sessionm.identity.api.data.SMPUser;
import com.sessionm.identity.api.provider.SessionMOauthProvider;
import com.sessionm.identity.api.provider.SessionMOauthTokenProvider;
import com.sessionm.smp_auth.BaseActivity;
import com.sessionm.smp_auth.R;
import com.sessionm.smp_auth.UserDetailsActivity;

import java.util.Set;

/**
 * Demonstrates the usage of the SMP SDK to authenticate a user with SessionM token.
 */
public class SessionMTokenActivity extends BaseActivity implements
        View.OnClickListener {

    private static final String TAG = "AuthenticateToken";

    //Sample user token generated by SessionM Identity provider
    private static final String SAMPLE_USER_TOKEN = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOiIyMDE3LTA5LTI3IDE1OjMwOjU1ICswMDAwIiwiZXhwIjoiMjAxNy0xMC0xMSAxNTozMDo1NSArMDAwMCIsImRhdGEiOnsiaWQiOiJkYTYxZGNkYS1hMzk4LTExZTctODcxZi05ZjZkNTQzYmUwNDAifX0.iBrHv9-INszE-SSL9rsuNnLDv7DBBaIUuqM6XDUvecxzap2CuoN4v3juXPvw-dZWuzbiHY2H3TPJJlRcI5_fZPxH2FjDqGA1S5nwEwEYVn9D1oMvnXUB6jLIq3ev4omE7ZUj5zVytsn_rKdryllfHro_8g5TneiOUoFBa_1N_RcC9AK_8640xbYPtZaNWhxsJiCwTsKWaLSYQ6RQv_xo1M4reL56dbjJ16Y-50HUy6Pxax6biKVvpjNRDizrkY0bka07lHMLAHMZD5-D3OYnxpxyg9aVX2kJd36iZuwsKaXVMtrCzwmzzGuhQD1PUUhC43wkNUbYw9z2d94v0FDxvQ";
    //Update this to be the access token you grabbed from SessionM Identity provider
    private static final String CUSTOM_USER_TOKEN = "";

    private TextView mStatusTextView;
    private TextView mDetailTextView;

    private SessionMOauthTokenProvider _sessionMOauthTokenProvider;
    private UserManager _userManager;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_sessionm_token);

        // Views
        mStatusTextView = findViewById(R.id.status);
        mDetailTextView = findViewById(R.id.detail);

        // Buttons
        findViewById(R.id.authenticate_with_sample_token_button).setOnClickListener(this);
        findViewById(R.id.authenticate_with_custom_token_button).setOnClickListener(this);
        findViewById(R.id.sign_out_button).setOnClickListener(this);

        findViewById(R.id.logged_in_view_profile).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                startActivity(new Intent(SessionMTokenActivity.this, UserDetailsActivity.class));
            }
        });

        _sessionMOauthTokenProvider = new SessionMOauthTokenProvider();
        SessionM.setAuthenticationProvider(_sessionMOauthTokenProvider, new AuthenticationProvider.OnAuthenticationProviderSetFromAuthenticationProvider() {
            @Override
            public void onUpdated(SessionMError sessionMError) {

            }
        });
        _userManager = UserManager.getInstance();
    }

    @Override
    public void onStart() {
        super.onStart();
    }

    private void authenticateWithToken(String token) {
        showProgressDialog();
        _sessionMOauthTokenProvider.authenticateWithToken(token, "sessionm_oauth", new SessionMOauthProvider.SessionMOauthProviderListener() {
            @Override
            public void onAuthorize(SessionMOauthProvider.AuthenticatedState authenticatedState, SessionMError sessionMError) {
                hideProgressDialog();
                if (sessionMError != null) {
                    Toast.makeText(SessionMTokenActivity.this, sessionMError.getMessage(), Toast.LENGTH_SHORT).show();
                }
                _userManager.fetchUser(new UserManager.OnUserFetchedListener() {
                    @Override
                    public void onFetched(SMPUser smpUser, Set<String> set, SessionMError sessionMError) {
                        if (sessionMError != null) {
                            Toast.makeText(SessionMTokenActivity.this, sessionMError.getMessage(), Toast.LENGTH_SHORT).show();
                        } else {

                            if (smpUser != null) {
                                // User is signed in
                                Log.d(TAG, "onAuthStateChanged:signed_in:" + smpUser.getID());
                            } else {
                                // User is signed out
                                Log.d(TAG, "onAuthStateChanged:signed_out");
                            }
                            updateUI(smpUser);
                        }
                    }
                });
            }
        });
    }

    private void signOut() {
        _sessionMOauthTokenProvider.logoutUser(null);
        updateUI(null);
    }

    private void updateUI(SMPUser smpUser) {
        hideProgressDialog();
        if (smpUser != null) {
            mStatusTextView.setText(getString(R.string.token_status_fmt, smpUser.getEmail()));
            mDetailTextView.setText(getString(R.string.smp_status_fmt, smpUser.getID()));

            findViewById(R.id.authenticate_with_sample_token_button).setVisibility(View.GONE);
            findViewById(R.id.authenticate_with_custom_token_button).setVisibility(View.GONE);
            findViewById(R.id.sign_out_button).setVisibility(View.VISIBLE);
            findViewById(R.id.logged_in_view_profile).setVisibility(View.VISIBLE);
        } else {
            mStatusTextView.setText(R.string.logged_out);
            mDetailTextView.setText(null);

            findViewById(R.id.authenticate_with_sample_token_button).setVisibility(View.VISIBLE);
            findViewById(R.id.authenticate_with_custom_token_button).setVisibility(View.VISIBLE);
            findViewById(R.id.sign_out_button).setVisibility(View.GONE);
            findViewById(R.id.logged_in_view_profile).setVisibility(View.GONE);
        }
    }

    @Override
    public void onClick(View v) {
        int i = v.getId();
        if (i == R.id.authenticate_with_sample_token_button)
            authenticateWithToken(SAMPLE_USER_TOKEN);
        else if (i == R.id.authenticate_with_custom_token_button) {
            authenticateWithToken(CUSTOM_USER_TOKEN);
        } else if (i == R.id.sign_out_button) {
            signOut();
        }
    }
}
